# -*- coding: utf-8 -*-
"""pdf2audio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V7IZ0oVE1yku__Lt53huy0wOz2bJ9GHl
"""

#shashank

! pip install path pydub
! pip install PyPDF4
! pip install pyttsx3 SpeechRecognition

from path import Path
from PyPDF4.pdf import PdfFileReader as PDFreader, PdfFileWriter as PDFwriter
import pyttsx3
from speech_recognition import Recognizer, AudioFile
from pydub import AudioSegment
import os

! pip install requests

from urllib.request import urlopen
from urllib.error import URLError
from urllib.request import Request

url = input('enter URL ')
req = Request(url)
try:
    response = urlopen(req)
except URLError as e:
    if hasattr(e, 'reason'):
        print ('We failed to reach a server.')
        print ('Reason: ', e.reason)
    elif hasattr(e, 'code'):
        print ('The server couldn\'t fulfill the request.')
        print ('Error code: ', e.code)
else:
    print ('URL is good!')

import requests

import urllib.request
pdf_path = req
def download_file(download_url, filename):
    response = urllib.request.urlopen(download_url)    
    file = open(filename + ".pdf", 'wb')
    file.write(response.read())
    file.close()
 
download_file(pdf_path, "Test")

! pip install PyPDF2

! pip install gtts

#read file 
import PyPDF2
from gtts import gTTS 
from IPython.display import Audio 
 
# creating a pdf file object
pdfFileObj = open('/content/Test.pdf', 'rb')
 
# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
 
# printing number of pages in pdf file
num_of_pages=pdfReader.numPages
s=""
for page_num in range(num_of_pages): 
 pageObj = pdfReader.getPage(page_num)
 speech = pageObj.extractText()
 s = s + str(speech)
tts = gTTS(s) 
tts.save('1.wav') 
sound_file = '1.wav'
Audio(sound_file, autoplay=True)



