# -*- coding: utf-8 -*-
"""pdf_to_audio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16EC9VTYf-KGG9iPL-junzs3y764fYB6j
"""

! pip3 install PyPDF2
! pip3 install pyttsx3

from google.colab import files
up=files.upload()

# importing required modules
import PyPDF2
import pyttsx3
 
# creating a pdf file object
pdfFileObj = open('/content/fin_irjmets1651468843.pdf', 'rb')
 
# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
 
#number of pages in pdf file
num_of_pages=pdfReader.numPages

for page_num in range(num_of_pages): 

  #speak = pyttsx3.init('Sapi5')
  # creating a page object
  pageObj = pdfReader.getPage(page_num)
  print(pageObj.extractText())
  # extracting text from page
  text = pageObj.extractText()
  # speak.say('hello niru i can speak')
  # speak.say(text)
  # speak.runAndWait()
 
# closing the pdf file object
pdfFileObj.close()